### ISSUE TITLE
chapter 8.4.2  最后一步访问 htpp://localhost无法访问

### ISSUE THREAD

**Issue by latermonk** [cloudnativebooks/cloud-native-istio#16]
chapter 8.4.2  最后一步访问 htpp://localhost无法访问

前边几步都正常，到最后一步访问 htpp://localhost无法访问  

不是应该访问 virtualbox 中的IP才行么？  是映射到本地了么？

但是我查了一下 本地 80端口没有监听

**Comment by sunvim** [comment]
将weather-gateway.yaml文件中的 VirtualService，DestinationRule 修改成同一个namespace即可，

从坑里爬出来了

**Comment by gudeyang1** [comment]
我改成相同namespace 本地还是没有监听80端口呀
```
[root@localhost install]# cat weather-gateway.yaml
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: weather-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: weather
spec:
  host: frontend
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-route
  namespace: weather
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/weather-gateway
  http:
  - match:
    - port: 80
    route:
    - destination:
        host: frontend
        port:
          number: 3000
        subset: v1

```

**Comment by sunvim** [comment]
是通过 ingress-gateway 暴露的, 查一下 istio-system下面的 ingress-gateway

**Comment by NutsArray** [comment]
怎么解决的呀？各位～

**Comment by gudeyang1** [comment]
修改了一下, 访问 IP:31380 可以打开了, 
照理说端口都应该是一样的, 可以`kubectl -n istio-system get service istio-ingressgateway -o jsonpath='{.spec.ports[?(@.name=="http2")].nodePort}'` 确认一下
```
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: weather-gateway
  namespace: istio-system
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
  - port:
      number: 80
      name: http
      protocol: HTTP
    hosts:
    - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: DestinationRule
metadata:
  name: frontend-dr
  namespace: weather
spec:
  host: frontend
  subsets:
  - name: v1
    labels:
      version: v1
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: frontend-route
  namespace: weather
spec:
  hosts:
  - "*"
  gateways:
  - istio-system/weather-gateway
  http:
  - match:
    - uri:
        prefix: /
    route:
    - destination:
        host: frontend.weather.svc.cluster.local
        port:
          number: 3000
        subset: v1
```
