### ISSUE TITLE
no matches for kind "metric" in version "config.istio.io/v1alpha2" 问题解决

### ISSUE THREAD

**Issue by kakj-go** [cloudnativebooks/cloud-native-istio#30]
## istio的metric创建指南
```
https://istio.io/docs/reference/config/policy-and-telemetry/templates/metric/
```

## customer-request-count.yaml我改成了如下所示
```yaml
apiVersion: "config.istio.io/v1alpha2"
kind: instance
metadata:
  name: customerrequestcount
  namespace: istio-system
spec:
  compiledTemplate: metric
  params:
    value: "1"
    dimensions:
      method: request.method | "unknown"
      path: request.path | "unknown"
      useragent: request.useragent | "unknown"
      destination: destination.service.name | "unknown"
      code: response.code | 200
    monitored_resource_type: '"UNSPECIFIED"'
---
apiVersion: "config.istio.io/v1alpha2"
kind: handler
metadata:
  name: prometheus
  namespace: istio-system
spec:
  compiledAdapter: prometheus
  params:
    metrics:
    - name: customer_request_count
      instance_name: customerrequestcount.instance.istio-system
      kind: COUNTER
      label_names:
      - method
      - path
      - useragent
      - destination
      - code
---
apiVersion: "config.istio.io/v1alpha2"
kind: rule
metadata:
  name: customerprom
  namespace: istio-system
spec:
  actions:
  - handler: prometheus
    instances: [ customerrequestcount ]

```
