### ISSUE TITLE
11.3.2 地域负载均衡  故障转移实战演练 dr 的hosts应该是写错了

### ISSUE THREAD

**Issue by mark8s** [cloudnativebooks/cloud-native-istio#41]
书中内容为：

```
spec:
  host: advertisement.weather.svc.cluster.local
  trafficPolicy:
    connectionPool:
      http:
        maxRequestsPerConnection: 1
```
实际上 hosts 应该是 recommendataion.weather.svc.cluster.local 才对，因为你此时是对recommendataion服务的访问。
